### ISSUE TITLE
snap breaks if /etc/get_iplayer/options exists

### ISSUE THREAD

**Issue by mattiaswerner** [Ads20000/get-iplayer#2]
Like title says, if there is a file located at /etc/get_iplayer/options, the snap fails to run with the error

"ERROR: Cannot read options file: /etc/get_iplayer/options"

If changing from apt installation to snap, this is a showstopper for a regular user.

**Comment by Ads20000** [comment]
Filed as https://github.com/snapcrafters/get-iplayer/issues/4
